### PR TITLE
Email Validation

### PR DESCRIPTION
**Pull request by Emmanuelaaron**
This adds a feature that enables an email to be valid
I have used regular expressions to validate the email
@nanfuka @ernesthenry @mderek227 @Manorlds-Eaglespark please review my PR before i can merge it

### CODE REVIEW

**Comment by nanfuka** [comment]
```@users_blueprint.route('/')
def index():
    return "you're welcome to ireporter"```

include the status
in your response data

**Comment by nanfuka** [comment]
great work Emma, i think you re good to go

**Comment by Emmanuelaaron** [comment]
okay thanks @nanfuka

**Comment by Manorlds-Eaglespark** [comment]
Well done Emma. Keep up this good work

**Pull request merged**
